INSERT INTO PRODUCTS (P_VENUE,P_DATE) values ('hybris Munich, Germany',now())
INSERT INTO PRODUCTS (P_VENUE,P_DATE) values ('hybris Montreal, Canada',now())
INSERT INTO PRODUCTS (P_VENUE,P_DATE) values ('hybris Boulder, USA',now())
INSERT INTO PRODUCTS (P_VENUE,P_DATE) values ('hybris London, UK',now())
INSERT INTO PRODUCTS (P_VENUE,P_DATE) values ('hybris Gliwice, Poland',now())
INSERT INTO PRODUCTS (P_VENUE,P_DATE) values ('hybris Boston, USA',now())
